accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

# accountapp : hello_world/

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),
    # 로그인
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    # 로그아웃
    path('logout/', LogoutView.as_view(), name='logout'),

    # 회원가입
    path('create/', AccountCreateView.as_view(), name='create'),

    # 회원정보 상세
    # 특정 유저의 정보 - primary key 가 필요하다 - 몇 번 user 객체에 접근할 것인지 명시해주어야 한다
    path('user_detail/<int:pk>', AccountDetailView.as_view(), name='user_detail'),

    # 정보 수정
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),

    # 정보 삭제
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

pragmatic/urls.py
# Routing - 특정 주소를 들어갔을 때, view 를 돌려줘야 한다
# 특정 주소를 만들어주는 작업 = urls.py
# 제일 먼저 요청을 받는 파일 !!!
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sentry-debug/', trigger_error),
    path('accounts/', include('accountapp.urls')),  # accountapps.urls.py 의 파일을 참조하여 안에서 다시 분기를 하는
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribes/', include('subscribeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profileapp/urls.py
from django.urls import path

from profileapp.views import ProfileCreateView, ProfileUpdateView

app_name = 'profileapp'

urlpatterns = [
    path('create/', ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>', ProfileUpdateView.as_view(), name='update'),

]

accountapp/models.py
from django.db import models

# python managepy makemigrations -- models.py 에 쓰는 내용을 DB와 연동시킬 python file 로 만들어주는 작업
# python manage.py migrate -- migration 적용


class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm

class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User # django 에서 기본으로 제공하는 (ctrl + b)
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render

# Check if authenticated
# Check request valid
# Collect data from DB
# Render response
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorators import account_ownership_required
from accountapp.forms import AccountUpdateForm
from articleapp.models import Article

"""
    Account
        1. Sign Up
        2. View info
        3. Change info
        4. Quit
"""
"""
    Class Based View (CBV)
    Function Based View (FBV)
"""
# def = define
# request 를 넣어서 response 에 답해준다
from django.urls import reverse, reverse_lazy

from accountapp.models import HelloWorld


has_ownership = [account_ownership_required, login_required]


@login_required # decorator
def hello_world(request):

        if request.method == "POST": # request 요청이 post 일 경우

            # request 중 POST request 에서 'hello_world_input' 이라는 name 의 input 을  가져온다
            temp = request.POST.get('hello_world_input')

            # models.py 에서 나온 HelloWorld 객체
            new_hello_world = HelloWorld()
            new_hello_world.text = temp # 변수의 text value
            new_hello_world.save()

            # data 전송이 종료되면 다시 GET 요청으로 돌아가게 한다
            return HttpResponseRedirect(reverse('accountapp:hello_world'))

        else: # get 요청일 경우에
            hello_world_list = HelloWorld.objects.all()
            return render(request, 'accountapp/hello_world.html', context={'hello_world_list': hello_world_list})


"""
    HTTP Protocol (request / response)
    : additional Data 를 처리하는 방식
    - GET -- inquiry (조회). 주소 안에 parameter 를 넣어서 처리해준다
    - POST -- create, update. 서버 내에 정보를 만들거나 수정할 때. 추가적으로 body 응답 내부에 있는 몸통에 data 를 넣어서 보낸다. 
    
"""

# 회원가입
class AccountCreateView(CreateView):
    model = User
    # User model 을 만드는 데 필요한 form
    form_class = UserCreationForm
    # 계정을 만드는 데 성공했다면 어느 경로로 보내줄 지
    success_url = reverse_lazy('accountapp:hello_world') # reverser_lazy 는 class base view 에서 사용
    # 어느 html file 을 이용해서 볼 지
    template_name = 'accountapp/create.html'

# 회원정보
class AccountDetailView(DetailView, MultipleObjectMixin):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/user_detail.html'

    paginate_by = 25

    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object())
        return super(AccountDetailView, self).get_context_data(object_list=object_list, **kwargs)

# 계정정보 수정
@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    model = User
    context_object_name = 'target_user'
    form_class = AccountUpdateForm
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/update.html'


# 계정 삭제
@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}

{% block content %}

    <div>
        <form action="{% url 'accountapp:create' %}" method="post"> {# accountapp 에 있는 create routing 으로 연결해라 #}
            {% csrf_token %} {# post 에는 항상 들어가야 된다 #}
            {{ form }}
            <input type="submit" class="btn btn-primary">
        </form>
    </div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div class="mb-4"> <!-- Margin bottom -->
            <h4>Quit</h4>
        </div>
        <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post"> {# accountapp 에 있는 create routing 으로 연결해라 #}
            {% csrf_token %} {# post 에는 항상 들어가야 된다 #}
            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

accountapp/templates/accountapp/hello_world.html
{% extends 'base.html' %}

{%  block content %}

    <!-- Middle -->
    <div style="border-radius: 1rem; margin: 2rem; text-align: center;">
        <h1 style="font-family: 'Playfair Display', cursive;">
            Hello, Here is Jinma Space!
        </h1>

        <form action="/account/hello_world/" method="post">
            {# POST 방식으로 요청을 보낼 때는 항상 csrf token 을 명시해주어야 한다 #}
            {% csrf_token %}
            <div>
                <input type="text" name="hello_world_input">
            </div>
            <div>
                <input type="submit" class="btn btn-primary" value="POST">
            </div>
        </form>

        {% if hello_world_list %}
            {% for hello_world in hello_world_list %}
                <h4>
                    {#  view.py 의 method 로부터 받은 hello_world_list #}
                    {{ hello_world.text }}
                </h4>
            {% endfor %}
        {% endif %}
    </div>

{%  endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div>
            <h4>Login</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
{#                {{ form }}#}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
        <div class="mb-4"> <!-- Margin bottom -->
            <h4>Change Information</h4>
        </div>
        <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post"> {# accountapp 에 있는 create routing 으로 연결해라 #}
            {% csrf_token %} {# post 에는 항상 들어가야 된다 #}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

accountapp/templates/accountapp/user_detail.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <div style="text-align: center; max-width: 300px; margin: 4rem auto;">
            <p>
                {{ target_user.date_joined }}
            </p>


            <!-- Profile 접근 경로 -->
            {% if target_user.profile %}

            <!-- Profile Image -->
            <img style="height: 10rem; width: 10rem; border-radius: 20rem; margin-bottom: 2rem; object-fit: cover;"
                 src="{{ target_user.profile.image.url }}" alt="">

                <h2 style="font-family: 'NanumSquareB">
                    {{ target_user.profile.nickname }}
                    {% if target_user == user %}
                        <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
                            Edit
                        </a>
                </h2>
                    {% endif %}

                <h5 style="margin-bottom: 3rem;">
                    {{ target_user.profile.message }}
                </h5>

            {% else %}
                   {% if target_user == user %}
                        <a href="{% url 'profileapp:create' %}">
                            <h2 style="font-family: 'NanumSquareB';">
                                Create Profile
                            </h2>
                        </a>
                   {% else %}
                        <h2>
                            닉네임이 설정되지 않은 사용자입니다.
                        </h2>
                   {% endif %}
            {% endif %}


            <!-- 계정 정보 수정/삭제 접근 경로 -->
            {% if target_user == user %} {# user = 지금 접속한 유저 #}
                <a href="{% url 'accountapp:update' pk=user.pk %}">
                    <p>
                        Change Information
                    </p>
                </a>
                <a href="{% url 'accountapp:delete' pk=user.pk %}">
                    <p>
                        Quit
                    </p>
                </a>
            {% endif %}
        </div>

        <div>
            {% include 'snippets/list_fragments.html' with article_list=object_list %}
        </div>
    </div>
{% endblock %}