accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

# accountapp : hello_world/

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'),
    # 로그인
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    # 로그아웃
    path('logout/', LogoutView.as_view(), name='logout'),

    # 회원가입
    path('create/', AccountCreateView.as_view(), name='create'),

    # 회원정보 상세
    # 특정 유저의 정보 - primary key 가 필요하다 - 몇 번 user 객체에 접근할 것인지 명시해주어야 한다
    path('user_detail/<int:pk>', AccountDetailView.as_view(), name='user_detail'),

    # 정보 수정
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),

    # 정보 삭제
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'

urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(template_name='articleapp/create.html'), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(template_name='articleapp/detail.html'), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(template_name='articleapp/update.html'), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(template_name='articleapp/delete.html'), name='delete'),
]

pragmatic/urls.py
# Routing - 특정 주소를 들어갔을 때, view 를 돌려줘야 한다
# 특정 주소를 만들어주는 작업 = urls.py
# 제일 먼저 요청을 받는 파일 !!!
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sentry-debug/', trigger_error),
    path('accounts/', include('accountapp.urls')),  # accountapps.urls.py 의 파일을 참조하여 안에서 다시 분기를 하는
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribes/', include('subscribeapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path

from projectapp.views import *

app_name = 'projectapp'

urlpatterns = [
    path('list/', ProjectListView.as_view(), name='list'),
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import *

app_name = 'subscribeapp'

urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}

<body style="font-family: 'NanumSquareR">
    <!-- Top -->
    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    <!-- Bottom -->
    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div class="pragmatic_footer">
    <div class="pragmatic_footer_button">
        <span>Notice</span> |
        <span>Collaboration</span> |
        <span>Service</span>
    </div>
    <div style="margin-top: 1rem;">
        <h6 class="logo">Pragmatic</h6>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Pragmatic</title>

    <!-- Bootstrap Link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <!-- Google Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display&display=swap" rel="stylesheet">

    <!-- Default CSS Link -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <!-- Naver font -->
    <style>
        @font-face {
            font-family: 'NanumSquareB';
            src: local('NanumSquareB');
            url("{% static 'fonts/NanumSquareB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareEB';
            src: local('NanumSquareEB');
            url("{% static 'fonts/NanumSquareEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareL';
            src: local('NanumSquareL');
            url("{% static 'fonts/NanumSquareL.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareR';
            src: local('NanumSquareR');
            url("{% static 'fonts/NanumSquareR.otf' %}") format("opentype");
        }
    </style>
</head>

templates/header.html
<div class="pragmatic_header">
    <div>
        <h1 class="logo">Pragmatic</h1>
    </div>
    <div class="pragmatic_header_navbar">
        <a href="{% url 'articleapp:list' %}" >
            <span>Articles</span>
        </a>
        <a href="{% url 'projectapp:list' %}" class="pragmatic_header_nav">
            <span>Projects</span>
        </a>
        <a href="{% url 'subscribeapp:list' %}" class="pragmatic_header_nav">
            <span>Subscription</span>
        </a>
        {% if not user.is_authenticated %}
            <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="pragmatic_header_nav">
                <span>Login</span>
            </a>
            <a href="{% url 'accountapp:create' %}" class="pragmatic_header_nav">
                <span>Sign Up</span>
            </a>
        {% else %}
            <a href="{% url 'accountapp:user_detail' pk=user.pk %}" class="pragmatic_header_nav">
                <span>MyPage</span>
            </a>
            <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" class="pragmatic_header_nav">
                <span>Logout</span>
            </a>
        {% endif %}
    </div>
</div>